routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
	Route::group(['prefix' => 'Administrador'], function(){
	
		Route::resource('User', 'Auth\UserController');
		Route::resource('Backlog', 'Backlog\BacklogController');
		Route::resource('Backlog_History', 'Backlog_history\Backlog_historyController');
		Route::resource('History', 'History\HistoryController');
		Route::resource('Project', 'Project\ProjectController');
		Route::resource('Sprint', 'Sprint\SprintController');
		Route::resource('Sprint_History', 'Sprint_history\Sprint_historyController');
		Route::resource('Task', 'Task\TaskController');
		Route::resource('Task_Sprint_User', 'Task_sprint_user\Task_sprint_userController');
		Route::resource('User_Rol_Project', 'User_Rol_Project\User_Rol_ProjectController');

		
});

		


Route::get('Administrador/Backlogs/{Backlogs}',[
			'as'	=>	'Backlogs.shows',
			'uses'	=>	'Backlog\BacklogController@index_show'
		]);

Route::get('Administrador/Historys/{Historys}',[
			'as'	=>	'Historys.shows',
			'uses'	=>	'History\HistoryController@index_show'
		]);

Route::get('Administrador/Tasks/{Tasks}',[
			'as'	=>	'Tasks.shows',
			'uses'	=>	'Task\TaskController@index_show'
		]);

Route::get('Administrador/Projects/{Projects}',[
			'as'	=>	'Projects.shows',
			'uses'	=>	'Project\ProjectController@index_show'
		]);

	
	 
Auth::routes();

Route::get('/home', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index');

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $table ="tasks";
    protected $fillable = ['name','description','file','fk_phase_id','fk_priority_id','fk_project_id'];
    protected $guarded = ["id"];

    public function User_Sprint_Tasks(){
         return $this->hasMany('App\Models\Task_Sprint_User','fk_task_id','id');
    }

    public function project()
    {
        return $this->belongsTo('App\Models\Project','fk_project_id','id');
    }

    public function phase_task()
    {
        return $this->belongsTo('App\Models\Phase_Task','fk_phase_id','id');
    }

    public function priority_task()
    {
        return $this->belongsTo('App\Models\Priority_Task','fk_priority_id','id');
    }
}

app/Http/Controllers/Task/TaskController.php
<?php

namespace App\Http\Controllers\Task;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Phase_Task;
use App\Models\Priority_Task;
use App\Models\Task;
use App\Models\Project;
use Laracasts\Flash\Flash;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        flash()->overlay('Tú no has podido acceder por URL, por favor inicia sesión o registrate', 'Error!!!');
        $this->middleware('auth');
        $this->middleware('revalidate');

    }
    public function index()
    {
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $tasks = new Task($request->all());   //almaceno todos los datos recibidos de la vista dentro de la variable  $backlog
        $tasks->save();  //guardo todo lo que contenga la variable backlog

        Flash::success('Se ha registrado la peticion "' . $tasks->name . '" exitosamente');  //creo un mensaje para la vista... posteriormente la vista recibira este contenido
        return redirect()->route('Tasks.shows', $request->fk_project_id);    //Redirecciono a la ruta donde consulto de manra especifica los backlogs dento de un proyecto
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        
        $tasks = Task::find($id); //busco el backlog que provenga de la vista mediante el $id que solicito en el formulario de la vista
        $type = Phase_Task::orderBy('name','ASC')->pluck('name', 'id')->toArray();      //consulto de manera general y ordeno de forma ascendiente lqs fases que tiene una tarea
        $priority = Priority_Task::orderBy('id','ASC')->pluck('name', 'id')->toArray();    //consulto de manera general y ordeno de forma ascendiente las prioridades de una tarea
        $project = Project::find($tasks->fk_project_id);  //busco el proyecto que provenga de la vista mediante el $id que solicito en el formulario de la vista
        $phase = Phase_Task::all();


        return view('Admin.Task.edit')   //Retorno a la vista 
        ->with('tasks', $tasks)       //con todo lo que contenga la variable $backlogs
        ->with('type', $type)               //con todo lo que contenga la variable $type
        ->with('priority', $priority) 
        ->with('phase', $phase)      //con todo lo que contenga la variable $priority
        ->with('project', $project);        //con todo lo que contenga la variable $project
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
            if($request->ajax()){
                
                return "AJAX";
            
            }else{

        $tasks = Task::find($id);     //busco el backlog que provenga de la vista mediante el $id que solicito en el formulario de la vista
        $tasks->fill($request->all());   //almaceno todos los datos recibidos de la vista dentro de la variable  $backlogs
        
        $tasks->save();                  //guardo todo lo que contenga la variable $backlogs
        $project = Project::find($tasks->fk_project_id);    // busco con el atriburo fk_project_id de la variable $backlog entre los proyectos exitentes


        flash('Se ha modificado la tarea "' . $tasks->name . '" exitosamente')->important();  //creo un mensaje para la vista... posteriormente la vista recibira este contenido
        return redirect()->route('Tasks.shows', $tasks->fk_project_id);   //Redirecciono a la ruta donde consulto de manra especifica los backlogs dento de un proyecto
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function index_show($id)
    {
        $type = Phase_Task::orderBy('name','ASC')->pluck('name', 'id')->toArray();      //consulto de manera general y ordeno de forma ascendiente lqs fases que tiene una tarea
        $priority = Priority_Task::orderBy('id','ASC')->pluck('name', 'id')->toArray();    //consulto de manera general y ordeno de forma ascendiente las prioridades de una tarea
        $project = Project::find($id);  //busco el proyecto que provenga de la vista mediante el $id que solicito en el formulario de la vista
        $phase = Phase_Task::with('tasks')->get();
        

        $tasks = Task::where('fk_project_id', $id)->orderBy('fk_priority_id','ASC')->get();    //codigo para consultar todos los backlogs que le pertenecen a un proyecto

        return View('Admin.Task.tasks')   //retorno a la vista de tasks
        ->with('tasks', $tasks)   //con todo lo que contenga la variable $backlogs 
        ->with('project', $project)     //con todo lo que contenga la variable $project
        ->with('type', $type)           //con todo lo que contenga la variable $type
        ->with('priority', $priority)  //con todo lo que contenga la variable $priority
        ->with('phase', $phase);
    }
}

resources/views/Admin/Task/edit.blade.php
    <nav class="side-navbar">
      <div class="side-navbar-wrapper">
        <div class="sidenav-header d-flex align-items-center justify-content-center">
          <div class="sidenav-header-inner text-center"><img src="{{asset('/img/Logoo.png')}}" alt="person" class="img-fluid rounded-circle">
            <h2 class="h5 text-uppercase">SS</h2><span class="text-uppercase">Scrum Sena</span>
          </div>
          <div class="sidenav-header-logo"><a href="index.html" class="brand-small text-center"> <strong class="text-primary">S</strong><strong class="text-primary">S</strong></a></div>
        </div>
        <div class="main-menu">
          <ul id="side-main-menu" class="side-menu list-unstyled">                  
            <li> <a href="{{route('Project.index')}}"> <i class="fa fa-tasks" aria-hidden="true"></i><span>Proyectos</span></a></li>
            <li> <a href="{{route('Historys.shows', $project->id)}}"><i class="fa fa-puzzle-piece" aria-hidden="true"></i><span>Historias</span></a></li>
            <li> <a href="{{route('Backlogs.shows', $project->id)}}"> <i class="fa fa-list" aria-hidden="true"></i><span>Peticiones</span></a></li>
            <li> <a href="{{route('History.index')}}"> <i class="fa fa-comments" aria-hidden="true"> </i><span>Chat </span></a></li>
            <li> <a href="{{route('History.index')}}"> <i class="fa fa-line-chart" aria-hidden="true"></i><span>Linea de tiempo</span></a></li>
            <li> <a href="{{route('Project.index')}}"> <i class="fa fa-cogs" aria-hidden="true"></i><span>Proyecto</span></a></li>
            <li>
                <a  href="{{ url('/logout') }}" 
                    onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                    
                        <i class="fa fa-sign-out"></i><span>Cerrar Sesion </span> 
                    
                </a>
                <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                     {{ csrf_field() }}
                </form>
            </li>
          </ul>
        </div>
        
      </div>
    </nav>
    
@extends('layouts.task')
    {{ $contador = 1}}
@section('title',  $project->name )

@section('idproject', $project->id)

@section('project', $project->name )

@section('content')
    <div class="container">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                                <h3 class="panel-title">Modificar tarea: {{$tasks->name}}</h3>

                            <div class="panel-body">
                                @if(count($errors) >0)
                                    <div class="alert alert-danger" role="alert">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{$error}}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif
                            @include('flash::message')
                                <div class="table-responsive">
                                   {!! Form::open(['route' => ['Task.update', $tasks->id], 'method' => 'PUT']) !!}

                                        <div class="form-group">
                                            {!! Form::label('name', 'Nombre') !!}
                                            {!! Form::text('name', $tasks->name, ['class' =>'form-control', 'requerid', 'placeholder' => 'Nombre de la tarea']) !!}
                                        </div>
                                        
                                        <div class="form-group">
                                            {!! Form::label('name', 'Descripcion') !!}
                                            {!! Form::textarea('description', $tasks->description, ['class' =>'form-control textarea-description', 'requerid', 'placeholder' => 'Descripcion de la peticion']) !!}
                                        </div>

                                        <div class="form-group">
                                            {!! Form::hidden('fk_project_id', $tasks->fk_project_id, ['class' =>'']) !!}
                                        </div>
                                        
                                        <div class="form-group">
                                            {!! Form::label('profiles', 'Tipo de requisito',[ 'class' => 'col-md-4 control-label']) !!}
                                            {!! Form::select('fk_phase_id', $type, $tasks->phase_task, ['class' => 'form-control type-select ', 'required']) !!}
                                        </div>
                                        <div class="form-group">
                                            {!! Form::label('fk_priority_id', 'Prioridad',[ 'class' => 'col-md-4 control-label']) !!}
                                            {!! Form::select('fk_priority_id', $priority, $tasks->priority_task, ['class' => 'form-control priority-select ', 'required']) !!}
                                        </div>                                 
                                                                           
                                        <div class="modal-footer">
                                          {!! Form::submit('Actualizar', ['class' =>'btn btn-info col-md-offset-5']) !!}
                                        </div>
                                    {!! Form::close() !!} 
                                </div>
                            </div>
                    </div>
                </div>

                

@endsection

@section('js')
<script>/*
    $('#Crear').on('shown.bs.modal', function () {
        $('.backlog-select', this).chosen({
            placeholder_text_single: "seleccione algo",
        });
    });*/
</script>
@endsection